# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SGPCA_cpp <- function(X, group_label, tau_reg, eta_reg, max_iter, tol, init_v) {
    .Call('_SGPCA_SGPCA_cpp', PACKAGE = 'SGPCA', X, group_label, tau_reg, eta_reg, max_iter, tol, init_v)
}

SGPCA_rs_cpp <- function(X, group_label, B, rho, tau_range, eta_range, max_iter, tol, mode, init_v) {
    .Call('_SGPCA_SGPCA_rs_cpp', PACKAGE = 'SGPCA', X, group_label, B, rho, tau_range, eta_range, max_iter, tol, mode, init_v)
}

